version: "3.7"
services:
# container backend da aplicação
  bemol_back:
    container_name: bemol_back
    build:
      context: .
      dockerfile: back.Dockerfile
    volumes:
      - php-data:/var/www/html
    ports: 
      - 8080:80
    networks:
      - net-bemol

  bemol_banco:
    container_name: bemol_banco
    image: mysql:5.6
    volumes:
      - db-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bemol
    networks: 
      - net-bemol

  bemol_front:
    container_name: bemol_front
    build:
      context: .
      dockerfile: front.Dockerfile
    ports: 
      - 8081:80
    networks:
      - net-bemol

networks:
  net-bemol:
    driver: bridge

volumes:
  db-mysql:
  php-data:
