version: "3.7"
services:
# container backend da aplicação
  backend:
    container_name: bemol_back
    build:
      context: .
      dockerfile: back.Dockerfile
    volumes:
      - ./back:/var/www/html
    ports: 
      - 8080:80
    networks:
      - net-bemol

  banco:
    container_name: bemol_banco
    image: mysql:5.6
    volumes:
      - db-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bemol
    networks: 
      - net-bemol

  frontend:
    container_name: bemol_front
    build:
      context: .
      dockerfile: front.Dockerfile
    # volumes:
      # - ./back:/var/www/html
    ports: 
      - 8081:80
    networks:
      - net-bemol

  # composer:
  #   restart: 'no'
  #   image: composer/composer
  #   command: install
  #   volumes:
  #     - ./back:/app

networks:
  net-bemol:
    driver: bridge

volumes:
  db-mysql:
